### ISSUE TITLE
Include a `stack.yaml` for easier compiling with known working versions

### ISSUE THREAD

**Issue by bwbaugh** [jtdaugherty/tart#1] opened 2017-08-14 19:49 UTC
Would there be any objection to having a `stack.yaml` file to make it simpler to compile this project with `stack install`?

This worked for me:

```yaml
resolver: lts-9.0
packages:
- .
extra-deps:
- brick-0.23
- vty-5.17
- word-wrap-0.4.1
```

----

I generated the above with `stack init --solver --resolver=lts-9.0` since using `--resolver=nightly` is crashing right now with:

```bash
$ stack init --solver --resolver=nightly
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- tart.cabal

Selected resolver: nightly-2017-08-14
Selected resolver: nightly-2017-08-14
Downloaded nightly-2017-08-14 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

**Comment by jtdaugherty** [comment] 2017-08-16 15:18
Since I do not use `stack`, I'm concerned that if I include this in the repository, it will ultimately become stale. If I include it in the repository I'd only be willing to include it in, say, an `unsupported/` subdirectory to make that clear - but then that makes me concerned I should probably not include it unless it's going to be updated from time to time.

**Comment by jtdaugherty** [comment] 2017-08-16 15:19
(I also don't know whether putting it in a subdirectory would even work with `stack`.)

**Comment by bwbaugh** [comment] 2017-08-16 16:45
Thanks for the reply! (And thanks for this program 😊)

I understand your reasoning. Of course do whatever you think is best, including closing this issue if you'd rather not support having a `stack.yaml`. It was thankfully simple enough to generate for this repo. Other programs can be much harder to compile by finding the correct set of versions for all of the dependencies that work together i.e., reproducible builds especially after a couple of years.

**Comment by jtdaugherty** [comment] 2017-08-16 19:09
I agree that reproducible builds are important, although `stack` isn't the only way to address that concern. Since this is a toy project I would rather start with a permissive set of dependency constraints and tighten them as people find out that builds aren't possible.

I'm glad you were able to generate a configuration easily. I'll close this since I don't support `stack`, but please let me know if anything else comes up!

**Closed as completed by jtdaugherty** 2017-08-16 19:09 UTC
