### ISSUE TITLE
Canvas hit detection is... clamped? / not behaving properly? when using WASD to navigate

### ISSUE THREAD

**Issue by LoganDark** [jtdaugherty/tart#16] opened 2022-04-01 03:41 UTC
While trying to edit relatively large canvases, the tools aren't drawing where I'm clicking if I move too far in any direction using WASD.

It's relatively OK but offset from my cursor by a constant amount. This amount changes depending on where I move the canvas using WASD. It reaches a certain point where it's impossible to draw too far to the right/etc because no matter how far I move the canvas it's still somehow limited by the physical edge of my terminal.

**Comment by jtdaugherty** [comment] 2022-04-01 04:31
Thanks for reporting this. I was able to reproduce it and it turns out to be a bug in `brick`. I'll update here once the bug is fixed.

**Comment by jtdaugherty** [comment] 2022-04-01 04:31
For now, though, you can avoid the bug just by not ending up with any of the canvas off of the left or top sides of the screen.

**Comment by jtdaugherty** [comment] 2022-04-01 05:04
This is now fixed via 05d8f9322adab6f75cad40b1127c303739b50fa8 and https://github.com/jtdaugherty/brick/commit/96f06bdfb4a4e91923dfe666b4a33372f14a6b5f. Thanks!

**Closed as completed by jtdaugherty** 2022-04-01 05:04 UTC
